### ISSUE TITLE
Commands not documented in Readme

### ISSUE THREAD

**Issue by SrMouraSilva** [moddevices/mod-host#10]
Hello, checking the source code I noticed some commands that are not documented in Readme

I believe the following list represents all commands supported by mod-host:
https://github.com/moddevices/mod-host/blob/299a3977476e8eb0285837fbd7522cec506a11de/src/mod-host.h#L54-L81

I'm developing [PluginsManager](https://pypi.org/project/PedalPi-PluginsManager/), a python library to control lv2 plugins (using mod-host). I intend in the future to give a greater support, so I need the information about the options implemented in mod-host.

**Comment by kjyv** [comment]
Seconding this, some commands also take a different argument list than what help/man page suggest. Please update the docs!

**Comment by SrMouraSilva** [comment]
Fixed by https://github.com/moddevices/mod-host/commit/1726ad06b11323da7e1aaed690ff8aef91f702b5#diff-04c6e90faac2675aa89e2176d2eec7d8 ?
