### ISSUE TITLE
Socket interface seems to be broken

### ISSUE THREAD

**Issue by kjyv** [moddevices/mod-host#14]
Trying to connect using nc or telnet to port 5555, I don't get any action or reponse. `echo "help" | nc localhost 5555` should return something, right? I'm using expect instead atm ..

**Comment by falkTX** [comment]
This connection was open to outside of localhost, but closed in 2f1b0673c8522dd1510cfaf8093b24ca78d45f74.

**Comment by kjyv** [comment]
I'm not sure how this is related? I'm using the most recent version including that commit. The connection is also from localhost, so in any case, before or after that commit, I should be able to connect.

**Comment by falkTX** [comment]
ah sorry, I misread.

the reason this is likely not working for you is because the code also expects a connection in $port +1 (so 5556 by default), for the host->socket data transmission.
See https://github.com/moddevices/mod-host/blob/7370fc7862b8626d000c928195499ef0328786a9/src/socket.c#L241

**Comment by kjyv** [comment]
Ok, interesting. So why is there a second socket, for the response? I would've expected for everything to go through one socket really. I've tried to connect to both separately but the behavior is the same, no response on either socket, nothing happening for commands.

**Comment by kjyv** [comment]
I've had a look with gdb and it seems that apart from having to open 5555 and 5556, the commands are sent with \n from nc or telnet, so I had to remove this trailing \n. I guess from mod-ui the commands are sent without. I can call commands that way now, but no response is sent, e.g. return codes for error handling. Is that normal?

**Comment by nettings** [comment]
I'm playing with mod-host and netcat/telnet as well. For me, something like this works just fine:
```
pi@pieight:~ $ cat configFoo.modhost 
add http://gareus.org/oss/lv2/fil4#stereo 0
add http://calf.sourceforge.net/plugins/Compressor 1
```
```
pi@pieight:~ $ while read -r line ; do echo -n "$line... "; echo $line | nc localhost 5555; echo ; sleep 1 ; done < configFoo.modhost 
```
I find that mod-host does not queue, so if you omit the "sleep", it might barf...

**Comment by nettings** [comment]
However, I can't seem to be able to get at any monitoring output.
If I open a monitoring port with
`netcat -l 7777`
and then do
`monitor localhost 7777 1`, nothing happens.
All param_monitor commands fail with -103.
The only lifesign I get from the monitor port is that when I do
`monitor localhost 7777 1`, my netcat terminates, apparently getting an EOF.

**Comment by nettings** [comment]
@falkTX, I don't understand your comment about the second port. When I start mod-host, it listens only on 5555/tcp. Only when I explicitly specify `--feedback-port` on the command line is that second port ever opened. Opening a telnet or netcat session on that port does not produce any output so far, and no input is accepted either. What is the purpose of this port?

**Comment by falkTX** [comment]
the feedback port option was added a few days ago ;)
I added that option specifically for cases like this.
if you don't know what it is used for, then you can now ignore it.

**Comment by falkTX** [comment]
I believe this issue is fixed now. Please update mod-host and confirm if it works for you now or not.

**Comment by kjyv** [comment]
seems to work fine for me

**Comment by falkTX** [comment]
thanks for confirming, closing the bug then.
