### ISSUE TITLE
some commands only work in interactive mode, not via telnet/netcat

### ISSUE THREAD

**Issue by nettings** [moddevices/mod-host#20]
Hi, I have a strange problem where some commands work fine in interactive mode, but not via telnet/netcat.
This is one: `connect effect_0:outR effect_1:in_r`. Succeeds in interactive, but throws a -205 every time I try it via the socket.
`save foo.txt` is another. Via the socket, it will freeze the telnet session, audio continues, no file ever appears. In interactive mode, it works correctly.

With the first example, I can't be completely sure if it isn't some weird character escaping thing, but the second one seems simple enough that it can't plausibly be eaten by any stupid 7bit channel in between...

**Comment by nettings** [comment]
`help` being another good example, as mentioned in #14.

**Comment by nettings** [comment]
Update: `save` via socket will not freeze, it merely doesn't give a reply. Hitting Enter gives me the prompt back. `load` fails more verbosely: "error: can't open the file". Even with a full path.

**Comment by nettings** [comment]
Forgot to mention: this is on a Raspberry Pi 3, so there might be subtle architecture oddities...

**Comment by falkTX** [comment]
ah, so on that case it might be because of the __ARM_ARCH_7A__ macro usage.
I've changed that now to one only used in MOD OS builds (see 27a07b1e4f48c659ba9140ab4daf8b18fdb9726d). Please update and let me know if it works.

**Comment by nettings** [comment]
Thanks for the hint! I'm out of my Pi lab until Thursday night, but I'll let you know by the end of the week.

**Comment by nettings** [comment]
That didn't change anything, except for the fact that now the connection stays open after sending a single line via netcat, which it didn't do before. But the socket commands described above still don't work over telnet, only in local interactive mode.

**Comment by falkTX** [comment]
Do you have a Duo connected to the same network? Is there anything else using the default port 5555?
I suggest trying a different port number, it works here at least.

```
$ ./mod-host -v -p 6666
mod-host ready!
received: output_data_ready
response: resp 0
received: output_data_ready
response: resp 0
```

```
$ echo -n "output_data_ready" | nc localhost 6666 && echo
resp 0
$ echo -n "output_data_ready" | nc localhost 6666 && echo
resp 0
```

**Comment by lpellegrini** [comment]
Hi! i'm having the same problem on my raspberry PI 3. I already changed the port but still receiving:

received: connect effect_0:left_out system:playback_1

response: resp -205

Any idea of what can be triggering this issue?

**Comment by falkTX** [comment]
if you're receiving a response, then for sure it's not the same issue.

**Comment by lpellegrini** [comment]
Thanks for your quick response.

The original report states that: 

> This is one: connect effect_0:outR effect_1:in_r. Succeeds in interactive, but throws a -205 every time I try it via the socket.

I think that is the same issue or am i missing something?

**Comment by falkTX** [comment]
hmm right, the issue initially was that but then evolved into something else.
how are you sending the commend via network?
the final newline might result in some issues like what you describe.

**Comment by lpellegrini** [comment]
Basically i'm just executing:
"NC localhost 6666" then typing "connect effect_0:left_out system:playback_1" and hitting return. At first i was trying to run it from a bash script and i thought that maybe there was something in the script that was triggering the issue, but then i saw that that was not the problem. Jack shows the ports and i can connect them using "jack_connect".

**Comment by falkTX** [comment]
yeah, this seems to be because of the last terminating character.
when using nc, mod-host receives 'help\n' instead of just 'help'.
I was able to reproduce the issue, fix incoming.

**Comment by lpellegrini** [comment]
Thanks @falkTX now it works perfectly!.

**Comment by nettings** [comment]
I can confirm it now works when I send commands like this:
`echo -n "connect effect_0:outL system:playback_1" | nc localhost 6666 && echo`
`resp 0`

But it still doesn't work with telnet:
```
pi@pieight:~ $ telnet localhost 6666
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
connect effect_0:outL system:playback_3
resp -205
```
The output of mod-host -v on another console confirms @falkTX' diagnosis:
```
received: add http://gareus.org/oss/lv2/fil4#stereo 0
response: resp 0
received: connect effect_0:outL system:playback_1
response: resp 0
received: connect effect_0:outR system:playback_2
response: resp 0
received: param_set 0 gain -4
response: resp 0
received: param_get 0 gain
response: resp 0 -4.0000
received: connect effect_0:outL system:playback_3

response: resp -205
```
Note the extra newline after the failed command.

So yes, the socket interface is now usable and returns parameter values as well, but it still isn't robust enough to work with telnet. Since that is the first thing many people use when debugging plaintext socket communication, can I suggest that this bug is reopened? Or should I file a feature request?
And I still wonder why some commands worked before even with stray newlines, such as param_get and add, whereas connect and param_get didn't work. That created a lot of confusion on my part and suggests some underlying problem with string sanitizing...

**Comment by nettings** [comment]
Looks like telnet uses DOS-style CRLF. Purging carriage returns in addition to newlines seems to fix it:

```
pi@pieight:~/build/mod-host $ git diff
diff --git a/src/utils.c b/src/utils.c
index ad2a07d..45bf0cf 100644
--- a/src/utils.c
+++ b/src/utils.c
@@ -112,7 +112,7 @@ static void trim_spaces(char *str)
     while (1)
     {
         c = *(--pstr);
-        if (c == ' ' || c == '\t' || c == '\n') *pstr = 0;
+        if (c == ' ' || c == '\t' || c == '\n' || c == '\r') *pstr = 0;
         else break;
     }
 }

```
@falkTX, can I ask you to add this? It's probably faster to do it by hand than me creating a pull request :)

**Comment by falkTX** [comment]
Added that juts now. Let me know how it works

**Comment by nettings** [comment]
Like I said, seems to fix it :) Thanks for the quick reply.
