### ISSUE TITLE
Load plugins on localhost

### ISSUE THREAD

**Issue by lazzarello** [moddevices/mod-host#22]
How does the URL feature work? I tried to write a URL to a plugin on localhost with the following syntax `file:///usr/lib/lv2/plugin.lv2` and mod-host replies with an invalid URL error.

**Comment by falkTX** [comment]
It's not a URL, it's a URI (unique resource identifier).
That's how LV2 plugins identify themselves, each one has a unique ID on the entire system.
Run `lv2ls` to get a list of available plugins.
Then you can pass this to mod-host `add` command.

Small tip, it might be good for you to learn about LV2 plugins before to try to load random stuff in mod-host. Understanding what an LV2 plugin is and how they're made will help you understand how mod-host works too.
