### ISSUE TITLE
first compilation: error: readline/readline.h: No such file or directory

### ISSUE THREAD

**Issue by tom4tom** [moddevices/mod-host#24]
could be a beginners fault ;-), ToM

arm-mod-linux-gnueabihf-gcc -I/home/tmaier/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include -I/home/tmaier/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/lilv-0 -I/home/tmaier/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/serd-0 -I/home/tmaier/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sord-0 -I/home/tmaier/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sratom-0   -I/home/tmaier/mod-workdir/plugins-dep/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include   -DHAVE_FFTW335 -DHAVE_NEW_LILV -O3 -D__MOD_DEVICES__ -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -ffast-math -fno-finite-math-only -fprefetch-loop-arrays -funroll-loops -funsafe-loop-optimizations -isystem /home/tmaier/mod-workdir/plugins-dep/staging/usr/include -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/mod-host.o src/mod-host.c
src/mod-host.c:39:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.

**Comment by ricardocrudo** [comment]
You need to install the readline development libraries. I'll close the issue as it is not a mod-host problem, but we can still talk here if you need help.
