### ISSUE TITLE
Pass through midi notes?

### ISSUE THREAD

**Issue by kjyv** [moddevices/mod-host#25]
I wonder why it is not possible to pass through midi notes to loaded effects, possibly connecting a midi channel to an effect instance with a command. I've so far connected midi input to mod-host and effects separately. I've come to notice this is sub-optimal since most synths (juce based and others) simply use all midi input and pass it to the engine same as when running standalone. This leads to the problem that CC values that are mapped to params in mod-host also get changed again within the synth from the midi message directly (if they are mapped there e.g. from previous standalone usage). One could argue that synths need to check if they're running as lv2 and ignore midi cc but in fact most are not doing that. One way would be pass all midi to the effect through mod-host except cc messages (as they can/are mapped to params directly anyway). Then only one jack connection between device and mod-host is necessary.

**Comment by falkTX** [comment]
If plugins read midi cc and change their own parameters, then they are breaking the lv2 spec and should be considered broken.
We should not place workaround in hosts because plugins are just broken. Fix the plugins or don't use them.

**Comment by falkTX** [comment]
Since some commits ago, MIDI stuff is passed-through when the plugin is bypassed.
