### ISSUE TITLE
Glitches using host-sync with all step-seq varients

### ISSUE THREAD

**Issue by devcurmudgeon** [moddevices/mod-host#27]
Using this [pedal board](https://pedalboards.moddevices.com/pedalboards/5b7859202564d41ec16278c1), i hear occasional irregularities in the pattern.

This is true if I boot the mod into the board already rolling, as well as when I stop and start the transport via footswitch 1. First glitch on restart usually happens on beat 32..33

**Comment by devcurmudgeon** [comment]
This was discussed quite extensively on the #lv2 freenode channel. As I understand it MOD is sending rounded bar_beat values rather than true float values (eg. https://paste.baserock.org/mujifudidi)

**Comment by jkbd** [comment]
Thank you for the detailed problem description. I checked @falkTX changes and found no hickups in 96 bars time.
