### ISSUE TITLE
problem understanding how to load a plugin

### ISSUE THREAD

**Issue by jgastonraoul** [moddevices/mod-host#34]
Hi,

I've a problem to understand how to load a local plugin.

I've a plugin located under /home/pi/.lv2/GigaVerb.lv2 and I try to load it in mod-host (with interactive mode) using the command : 
`add file:///home/pi/.lv2/GigaVerb.lv2/GigaVerb.lv2 0`

I receive an error : 

```
can't get plugin
resp -101
```

I'm sure I miss something, but I don't know what... Can you help me ?

Regards,

Jérémie

**Comment by falkTX** [comment]
Does `lv2ls` show the plugin?

**Comment by jgastonraoul** [comment]
Hi !

Thanks for your reply, which put me on the right path...

The right syntax was : 
`add urn:maxgen:GigaVerb 0`

The URI was the one I found using `lv2ls`.

how can I list and control params from an instance ?

**Comment by falkTX** [comment]
`lv2info <plugin-uri` on the CLI will show you all the important info about a plugin

the rest, please just check the documentation, it is pretty clear:
```
param_set <instance_number> <param_symbol> <param_value>
    * set a value to given control
    e.g.: param_set 0 gain 2.50

param_get <instance_number> <param_symbol>
    * get the value of the request control
    e.g.: param_get 0 gain
```
