### ISSUE TITLE
Abrir mod-host mediante script.

### ISSUE THREAD

**Issue by fernando-inf** [moddevices/mod-host#46]
Hola, creo que lo que intento hacer no es posible:

Busco generar un script (#!/bin/bash) que automáticamente inicie mod-host  con un plugin LV2 y le asigne a este un Midi CC en un determinado <param_symbol>. 

Es la unica forma en que me resultaría útil mod-host, pero parece que no es posible.  Si alguien tiene alguna idea coméntela. Busco un Host LV2 liviano con posibilidad de asignar Midi CC  a los plugins.

**Comment by falkTX** [comment]
Please use english.

and this is easily possible:
```
mod-host
sleep 1
echo -e "add urn:zamaudio:ZamComp 0\n" | nc localhost 5555 -W 1
echo -e "midi_map 0 rel 0 7 1.0 500.0\n" | nc localhost 5555 -W 1
```

this loads zam compressor and maps its release parameter to CC 7 on channel 1.
see the `midi_map` on the readme for the arguments on these commands.

**Comment by fernando-inf** [comment]
Thanks for answering, but I needed to use mod-host in interactive mode and with "BASH" I couldn't. Today I found the solution using "EXPECT", this is the script (I'm not a developer ), hope it helps someone else, I have 125MB (approximately) of RAM in use: 

` #!/usr/bin/expect -f

set timeout -1;

spawn mod-host -i;

send "add https://github.com/lucianodato/noise-repellent 1\n" ; #add <lv2_uri> <instance_number>
expect "resp 1";

send "midi_map 1 noise_learn 0 1 0 1\n"; #midi_map <instance_number> <param_symbol> <midi_channel: channel 1= 0> <midi_cc> <minimum> <maximum>
expect "resp 1";


send "param_set 1 noise_learn 1\n" ; #param_set <instance_number> <param_symbol> <param_value>
expect "resp 0";

sleep 1
send "param_set 1 noise_learn 0\n";  #param_set <instance_number> <param_symbol> <param_value>
expect "infinito"; `
