### ISSUE TITLE
mod-monitor is now running by default

### ISSUE THREAD

**Issue by MaxPayne86** [moddevices/mod-host#52]
I'm testing hotfix-1.11 and noticed mod-monitor is now launched by main mod-host module and can no longer disabled. This could have been introduced earlier in the code, need to check.

This ends up in having mod-monitor module always between the last plugin output port and system:playback_*

In mono, this results in following jack routing

system:capture_1 -> effect_1:in -> effect_1:out -> effect_2:in -> effect_2:out -> mod-monitor:in_1 -> mod-monitor:out_1 -> system:playback_1

while on mod-ui interface right outputs are reported as Hardware Playback 1 (misleading)

I see mod-monitor implements a compressor functionality, however there are no controls on mod-ui for the parameters of this effect so I assume that is controlled by the moddevices hw hmi somehow.

I cannot find any documentation on this functionality both in mod-host and mod-ui source codes, please let me know otherwise.

[NOTE] derivative moddevices projects may prefer to not use mod-monitor/compressor

**Comment by falkTX** [comment]
what is the issue here?

the compressor and noisegate are not enabled on regular builds because of the lack of such controls

**Comment by MaxPayne86** [comment]
hello, is source code for those builds avail? If so I was totally unaware of that, sorry. I'm working on a custom meta-moddevices yocto layer I want to publish and I'm testing build with support to hotfix-1.11. My issue is I see mod-monitor running when I execute

jack_load mod-host

where previously I had to do
jack_load mod-host
jack_load mod-monitor

if compressor & volume functionalitites are disabled by default then mod-monitor is a pass-thru only or it serve for functionalities I don't know?

Thx

**Comment by falkTX** [comment]
things have just changed for convenience.
previously we needed to load mod-monitor manually, now we dont.

it is mainly there to make it easier to connect a peakmeter at the end, and to ensure we always have "output/playback" ports even if the device does not.

**Comment by MaxPayne86** [comment]
Okay, it serves as a dummy playback port for the effect chain, thanks. Do you have plans for compressor/volume controls from mod-ui? Would be nice to have noise gate (input) and compressor (output) as "system wide". It overlaps a bit with driver codecs that have such functionalitites (in input mostly) but then there would be hw deps...

**Comment by falkTX** [comment]
No direct plans for that atm

**Comment by MaxPayne86** [comment]
Doc provided by maintainer, closing
