### ISSUE TITLE
JackTickDouble undeclared

### ISSUE THREAD

**Issue by quochuy** [moddevices/mod-host#55]
When running make on Ubuntu 18 or 20 it fails with that error.
What's the previous version that works on those distros?

**Comment by ajboni** [comment]
Hi, im getting the same with `pipewire-jack` on arch linux. Does that means that  it is outdated vs jack2?

**Comment by falkTX** [comment]
pipewire likely has old jack2 based headers, before these additions were added.
fill a bug report with them.

FYI both latest jack1 and jack2 provide these definitions since quite some time now.

**Comment by Lotharyx** [comment]
It looks like you need to update your README.md to call out libjack-jackd2-dev version 1.9.19 or later, as that is the version that introduced JackTickDouble.  See https://jackaudio.org/news/2021/07/16/jack2-v1919-release.html

**Comment by danielappelt** [comment]
I have just opened [a ticket](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3181) in pipewire.

**Comment by wtay** [comment]
It should only use the field and flags when JACK_TICK_DOUBLE is defined.
