### ISSUE TITLE
pid file is annoying

### ISSUE THREAD

**Issue by worikgh** [moddevices/mod-host#64]
Having exach instance of mod-host trying to open the same file to store a PID (why?) is annoying for those of us who run it as different users.

I have an instance of mod-host run by modep-mod-host service, and I run an instance (on a different port) for other reasons.

So they collide over /tmp/mod-host.pid

**Comment by falkTX** [comment]
mod-host uses globally unique jack client names, it is how it identifies certain effects.
running multiple instances of mod-host is not supported
