### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by renemadeira** [moddevices/mod-host#75]
I have a virtual studio for my band, one that every musician listens through earphones... It would be nice if I could run multiple instances of mod-host, connected to the same jack session, but each with some input/output available. Then each musician would have an instance of mod-ui served in different ports, so everyone would be able to set his own chain separately. It doesn't seem to be feasible in current documentation. Is it an improvement that the mod team would be interested? I'm not a professional developer, but I can do some coding. Can anyone point me in the right direction? Thanks!

**Comment by falkTX** [comment]
it is not within scope of the project. you could try to setup multiple jack servers each with their own server name, but explaining all this in detail is also out of scope for mod-host (and anyhow it really gets tricky to manage).
